from uuid import uuid4
from pydantic import BaseModel, Field, field_validator
from datamart_analytics.definitions.custom_definitions import (
    SnowflakeAuthenticatorType,
    UpsertResultStatus,
)


class SnowflakeCredentials(BaseModel):
    """
    Configuration class for Snowflake credentials.
    This class uses Pydantic's BaseModel to manage Snowflake credentials.
    """

    user: str = Field(..., description="Snowflake user name")
    password: str | None = Field(
        default=None, description="Snowflake password (optional for SSO)"
    )
    account: str = Field(..., description="Snowflake account name")
    warehouse: str = Field(..., description="Snowflake warehouse name")
    database: str = Field(..., description="Snowflake database name")
    table_schema: str = Field(
        default="DBO", description="Snowflake schema name for the database"
    )
    role: str = Field(..., description="Snowflake role name")
    authenticator: SnowflakeAuthenticatorType | None = Field(
        default=None,
        description="Authentication method (e.g., 'snowflake' or 'externalbrowser')",
    )
    private_key_file: str | None = Field(
        default=None,
        description="Path to the private key file for key pair authentication",
    )
    private_key_password: str | None = Field(
        default=None, description="Password for the private key file"
    )


class DatamartTable(BaseModel):
    """
    Configuration class for the DataMart Tables.
    This class represents the configuration for a DataMart table, including source and target database, schema, and table information.
    """

    name: str = Field(..., description="Name of the datamart")
    source_database: str = Field(..., description="Source database name")
    source_schema: str = Field(..., description="Source schema name")
    source_warehouse: str | None = Field(default=None, description="Source warehouse name (optional)")
    source_table: str | None = Field(default=None, description="Source table name (optional)")
    target_database: str = Field(..., description="Target database name")
    target_schema: str = Field(..., description="Target schema name")
    target_warehouse: str = Field(..., description="Target warehouse name")
    target_table: str | None = Field(default=None, description="Target table name (optional - reports may create multiple tables)")
    carrier_name: str = Field(..., description="Carrier name")
    last_load_date: str | None = Field(
        default=None,
        description="Last load date for incremental data extraction (format: 'YYYY-MM-DD HH:MM:SS').",
    )
    report_start_dt: str | None = Field(
        default=None, description="Report start datetime (YYYY-MM-DD HH:MM:SS)"
    )
    report_end_dt: str | None = Field(
        default=None, description="Report end datetime (YYYY-MM-DD HH:MM:SS)"
    )
    as_of_run_dt: str | None = Field(
        default=None, description="As of run datetime (YYYY-MM-DD HH:MM:SS)"
    )
    report_run_dt: str | None = Field(
        default=None, description="Report run datetime (YYYY-MM-DD HH:MM:SS)"
    )

    @field_validator(
        "source_database",
        "source_warehouse",
        "source_schema",
        "source_table",
        "target_database",
        "target_schema",
        "target_warehouse",
        "target_table",
    )
    @classmethod
    def convert_to_upper(cls, value: str | None) -> str | None:
        """
        Convert the value to uppercase.

        This method is used to ensure that all database, schema, and table names are in uppercase.
        Cannot cover carrier name as it is case sensitive in the SQL queries.
        Handles optional fields by returning None if value is None.

        Params:
            value: The string value to convert to uppercase, or None.

        Returns:
            The uppercase version of the input string, or None if input is None.
        """
        if value is None:
            return None
        return value.upper()


class ExecutionLog(BaseModel):
    """
    Configuration class for execution logs.
    This class represents the configuration for execution logs, including the log file path and the log level.
    """

    execution_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique identifier for the execution log (autogenerated UUID)",
    )
    execution_start_ts: str = Field(
        description="Timestamp of the execution log in ISO format",
    )
    execution_end_ts: str | None = Field(
        default=None,
        description="End timestamp of the execution log in ISO format",
    )
    execution_status: str = Field(
        description="Status of the execution (e.g., 'success', 'failure')",
    )
    source_database: str = Field(
        description="Source database name for the execution log",
    )
    source_warehouse: str = Field(
        description="Source warehouse name for the execution log",
    )
    source_schema: str = Field(
        description="Source schema name for the execution log",
    )
    target_database: str = Field(
        description="Target database name for the execution log",
    )
    target_warehouse: str = Field(
        description="Target warehouse name for the execution log",
    )
    target_schema: str = Field(
        description="Target schema name for the execution log",
    )
    target_table: str = Field(
        description="Target table name for the execution log",
    )
    records_inserted: int = Field(
        default=0, description="Number of records inserted during the execution"
    )
    records_updated: int = Field(
        default=0, description="Number of records updated during the execution"
    )
    records_deleted: int = Field(
        default=0, description="Number of records deleted during the execution"
    )
    carrier_name: str = Field(description="Carrier name for the execution log")
    error_message: str | None = Field(
        default=None, description="Error message if the execution failed"
    )


class UpsertResult(BaseModel):
    """
    Result of an upsert operation.
    This class represents the result of an upsert operation, including the number of records inserted, updated, and deleted.
    """

    status: UpsertResultStatus = Field(
        description="Status of the upsert operation"
    )
    source_table: str = Field(
        description="Source table name for the upsert operation"
    )
    target_table: str = Field(
        description="Target table name for the upsert operation"
    )
    join_keys: list[str] = Field(
        description="List of join keys used in the upsert operation"
    )
    update_columns: list[str] | None = Field(
        default=None, description="List of columns updated during the upsert"
    )
    insert_columns: list[str] | None = Field(
        default=None, description="List of columns inserted during the upsert"
    )
    delete_columns: list[str] | None = Field(
        default=None, description="List of columns deleted during the upsert"
    )
    when_matched_condition: str | None = Field(
        default=None, description="Condition for when matched in the upsert"
    )
    when_not_matched_condition: str | None = Field(
        default=None, description="Condition for when not matched in the upsert"
    )
    use_when_matching_condition: bool = Field(
        default=False, description="Whether to use the WHEN MATCHED condition"
    )
    use_when_not_matching_condition: bool = Field(
        default=False, description="Whether to use the WHEN NOT MATCHED condition"
    )
    records_inserted: int = Field(
        default=0, description="Number of records inserted during the upsert"
    )
    records_updated: int = Field(
        default=0, description="Number of records updated during the upsert"
    )
    records_deleted: int = Field(
        default=0, description="Number of records deleted during the upsert"
    )
    method: str = Field(
        default="SQL_MERGE",
        description="Method used for the upsert operation.",
    )


class DatamartTable_integrated(BaseModel):
    """
    Configuration class for the DataMart Tables.
    This class represents the configuration for a DataMart table, including source and target database, schema, and table information.
    """

    source_database: str = Field(..., description="Source database name")
    warehouse: str = Field(..., description="warehouse name")
    target_database: str = Field(..., description="Target database name")
    target_schema: str = Field(..., description="Target schema name")
    carrier_name: str = Field(..., description="Carrier name")
    carrier_type: str = Field(..., description="Type of carrier used for the DataMart table")
    folder_name: str = Field(..., description="Folder name where the SQL files are located")
    report_start_dt: str | None = Field(
        default=None, description="Report start datetime (YYYY-MM-DD HH:MM:SS)"
    )
    report_end_dt: str | None = Field(
        default=None, description="Report end datetime (YYYY-MM-DD HH:MM:SS)"
    )
    as_of_run_dt: str | None = Field(
        default=None, description="As of run datetime (YYYY-MM-DD HH:MM:SS)"
    )
    report_run_dt: str | None = Field(
        default=None, description="Report run datetime (YYYY-MM-DD HH:MM:SS)"
    )
    # load_type: str = Field(..., description="full load or incremental load")

    @field_validator(
        "source_database",
        "target_database",
        "warehouse",
        "target_schema",
        # "load_type",
    )
    @classmethod
    def convert_to_upper(cls, value: str) -> str:
        """
        Convert the value to uppercase.

        This method is used to ensure that all database, schema, table and carrier names are in uppercase.
        """
        return value.upper()

    @field_validator("folder_name")
    @classmethod
    def convert_to_lower(cls, value: str) -> str:
        """
        Convert the value to lowercase.

        This method is used to ensure that all database, schema, table, and carrier names are in lowercase.
        """
        return value.lower()


class TableConfiguration(BaseModel):
    """
    Configuration class for a table.
    """

    name: str = Field(..., description="Name of the Table")
    source_table_name: str | None = Field(
        default=None, description="Source table name for the Table"
    )
    target_table_name: str = Field(..., description="Target table name for the Table")
    join_keys: list[str] = Field(..., description="List of join keys for the Table")
    update_columns: list[str] | None = Field(
        default=None, description="List of columns to update in the Table"
    )
    insert_columns: list[str] | None = Field(
        default=None, description="List of columns to insert in the Table"
    )
    when_matched_condition: str | None = Field(
        default=None,
        description="Condition for when matched in merge for the Table",
    )
    when_not_matched_condition: str | None = Field(
        default=None,
        description="Condition for when not matched in merge for the Table",
    )


class DatamartConfiguration(BaseModel):
    """
    Configuration class for DataMart.
    """

    tables: list[TableConfiguration] = Field(
        default_factory=list, description="List of DataMart table configurations"
    )
